import { HelloWorld } from './chap_1_firsts/01_hello_world';
import { MeshBuilder } from './chap_1_firsts/02_meshBuilder';
import { Material } from './chap_1_firsts/03_material';
import { Animation } from './chap_1_firsts/05_animation';
import { Sprite } from './chap_1_firsts/06_sprite';
import { Collisions } from './chap_1_firsts/07_collisions';
import { SkullGame } from './chap_1_firsts/07_skullGame';
import { SkyBox } from './chap_1_firsts/08_skyBox';
import { Particle } from './chap_1_firsts/09_particle';
import './style.css';

// new HelloWorld();
// new MeshBuilder();
// new Material();
// new Animation();
// new Sprite();
// new Collisions();
// new SkullGame();
// new SkyBox();
new Particle();