import './style.css';
import { HelloWorld } from './basic/01_hello_world';
import { MeshBuilder } from './basic/02_meshBuilder';
import { Material } from './basic/03_material';
import { Animation } from './basic/05_animation';
import { Sprite } from './basic/06_sprite';
import { Collisions } from './basic/07_collisions';
import { SkullGame } from './basic/07_skullGame';
import { SkyBox } from './basic/08_skyBox';
import { Particle } from './basic/09_particle';
import { Fog } from './basic/09_fog';
import { RainAndSnow } from './basic/09_rainAndSnow';
import { Raycaster } from './basic/10_raycaster';
import { ShootingGame } from './basic/10_shootingGame';
import { CollideGame } from './basic/10_collideGame';
import { Sound } from './basic/11_sound';

// new HelloWorld();
// new MeshBuilder();
// new Material();
// new Animation();
// new Sprite();
// new Collisions();
// new SkullGame();
// new SkyBox();
// new Particle();
// new Fog();
// const snow = new RainAndSnow();
// snow.windSpeed.x = 2;
// snow.windSpeed.z = -1;
// snow.mass = 0.01;
// new Raycaster();
// new CollideGame();
new ShootingGame();
// new Sound();