import { HelloWorld } from './chap_1_firsts/01_hello_world';
import { MeshBuilder } from './chap_1_firsts/02_meshBuilder';
import { Material } from './chap_1_firsts/03_material';
import { Animation } from './chap_1_firsts/05_animation';
import { Sprite } from './chap_1_firsts/06_sprite';
import { Collisions } from './chap_1_firsts/07_collisions';
import { SkullGame } from './chap_1_firsts/07_skullGame';
import { SkyBox } from './chap_1_firsts/08_skyBox';
import { Particle } from './chap_1_firsts/09_particle';
import { Fog } from './chap_1_firsts/09_fog';
import { RainAndSnow } from './chap_1_firsts/09_rainAndSnow';
import { Raycaster } from './chap_1_firsts/10_raycaster';
import { ShootingGame } from './chap_1_firsts/10_shootingGame';
import { CollideGame } from './chap_1_firsts/10_collideGame';
import './style.css';
import { Sound } from './chap_1_firsts/11_sound';

// new HelloWorld();
// new MeshBuilder();
// new Material();
// new Animation();
// new Sprite();
// new Collisions();
// new SkullGame();
// new SkyBox();
// new Particle();
// new Fog();
// const snow = new RainAndSnow();
// snow.windSpeed.x = 2;
// snow.windSpeed.z = -1;
// snow.mass = 0.01;
// new Raycaster();
// new CollideGame();
new ShootingGame();
// new Sound();